project_id = "ythqjhiyavgpghmoreiz"

[functions.newsletter-subscribe]
verify_jwt = false

[functions.newsletter-send-scheduled]
verify_jwt = false

[functions.newsletter-unsubscribe]
verify_jwt = false
