// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ythqjhiyavgpghmoreiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0aHFqaGl5YXZncGdobW9yZWl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5MDY4NDUsImV4cCI6MjA1NTQ4Mjg0NX0.0CDizUxC945oVlzdCoq0CBjxiwJq2oLBIli_nfRqghI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);