// AUTO-GENERATED by scripts/enrich_blog_posts.py — do not edit by hand.
// Run: python3 scripts/enrich_blog_posts.py [--force] [--only=slug]

export interface BlogPostExercise {
  title: string;
  description: string;
}

export interface BlogPostEnrichment {
  summary: string;
  keyPoints: string[];
  quotes: string[];
  exercises: BlogPostExercise[];
  aiGeneratedAt: string;
}

export const blogPostsEnrichment: Record<string, BlogPostEnrichment> = {};

export const getPostEnrichment = (slug: string): BlogPostEnrichment | undefined =>
  blogPostsEnrichment[slug];
